Feature/galc 43
AGH-Group-Management/gm-backend pull request #9
Opened 2024-04-06 15:55 UTC by Xavvee

2024-04-07 16:16 UTC, marcins1 requested changes

2024-04-07 16:16 UTC, marcins1 commented on src/main/java/agh/management/request/RequestController.java
> +        return null;
W klasach OtherRequestController, ChangeRequestController, VacationRequestController w metodach do tworzenia wniosków zwracasz ResponseEntity, ale nie zwracasz ich w tej metodzie.

2024-04-08 17:13 UTC, marcins1 requested changes

2024-04-08 17:13 UTC, marcins1 commented on src/main/java/agh/management/user/User.java
> +    private int id;
Po zmergowaniu nie zgadzają się typy tutaj i w klasach StudentDetailedInfoDTO, StudentShortInfoDTO.

2024-04-08 18:24 UTC, krzychsol approved these changes

2024-04-08 18:25 UTC, merged